cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: team-a502-bucket
    stack:
      auto: false
    credentials:
      access-key: AKIA2TBRAOMD4EYNB5MS
      secret-key: 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
      stack:
        auto: false
#cloud.aws.stack.auto=false

spring:
  profiles:
    include: oauth
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          naver:
            #scope: email
            client-id: DJ94WWgE_wFepnxDsIQa
            client-name: Naver
            #redirect-uri: https://i8a502.p.ssafy.io/oauth2/code/naver
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            #redirect-uri: http://localhost:3000/naver
            redirect-uri: http://localhost:8080/api/account/naver

            authorization-grant-type: authorization_code
            client-secret: U8bTHcjGRN
            scope:
              - name
              - email
          kakao:
            client-id: 5279f57dd9070bd649c59424bd9def46
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          google:
            client-id: 749119252630-dvt89n8869sr5f6spcllmhe3pb8tajhq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: 'true'

  application:
    name: oauth2

  datasource:
    password: '4913'
    username: ssafy
    url: jdbc:mysql://i8a502.p.ssafy.io:3306/mydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: '8080'

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      psc:
        sample: debug
